name: ssh command
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }}
           #- run: ssh tatsumasa_nakano@dev.marathon.rplearn.net bash /app/tatsumasa_nakano/deploy.sh tatsumasa_nakano
      - run: ssh ${{ steps.ssh.outputs.SERVER }} bash /app/tatsumasa_nakano/deploy.sh tatsumasa_nakano
